apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: fitness-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7-jammy
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: fit-volume
            mountPath: /data/db
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
        - name: fit-volume
          hostPath: 
            path: /ust
            type: Directory
          
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: fitness-app
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
 
 