apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-dashboard
  namespace: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollouts-dashboard
  template:
    metadata:
      labels:
        app: rollouts-dashboard
    spec:
      serviceAccountName: rollouts-dashboard-sa
      containers:
        - name: dashboard
          image: quay.io/argoproj/kubectl-argo-rollouts:latest
          command:
            - kubectl-argo-rollouts
            - dashboard
            - --host
            - 0.0.0.0
          ports:
            - containerPort: 3100
      

---

apiVersion: v1
kind: Service
metadata:
  name: rollouts-dashboard
  namespace: argo-rollouts
spec:
  type: NodePort
  selector:
    app: rollouts-dashboard
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 30100

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-dashboard-sa
  namespace: argo-rollouts

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollouts-dashboard-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollouts-dashboard-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollouts-dashboard-role
subjects:
- kind: ServiceAccount
  name: rollouts-dashboard-sa
  namespace: argo-rollouts

