# Global settings
namespace: fitness-app
app:
  replicaCount: 2
  image:
    repository: nmc9812/fitness-app
    tag: v1.1.4
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    targetPort: 5000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
mongodb:
  replicaCount: 1
  image: mongo:7-jammy
  pvcName: mongo-pvc
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
referenceGrant:
  fromNamespace: noel-ns
