apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: fit-volume
            mountPath: /data/db
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 10 }}
      volumes:
        - name: fit-volume
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.pvcName }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP