apiVersion: v1 
kind: ConfigMap 
metadata:
  name: fitness-configmap 
  namespace: {{ .Values.namespace }}
data:
  MONGODB_URI: "mongodb://mongodb-service.{{ .Values.namespace }}.svc.cluster.local:27017/fitness-tracker"
  PORT: "5000"
  HOST: "0.0.0.0"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: fit-secret
  namespace: {{ .Values.namespace }}
stringData:
  DD_TRACE_AGENT_PORT: "8126"
  DD_ENV: "production"
  DD_SERVICE: "fitness-tracker-app"
  DD_VERSION: "1.0.0"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: fitness-grant
  namespace: {{ .Values.namespace }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.referenceGrant.fromNamespace }}
  to:
    - group: ""
      kind: Service